# Generated by Django 2.0.4 on 2018-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_subtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
