# Generated by Django 2.0.4 on 2018-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180430_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pending',
        ),
        migrations.AddField(
            model_name='task',
            name='choice',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
