# Generated by Django 2.0.4 on 2018-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20180430_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], default=(('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')), max_length=10),
        ),
    ]
